name: docker build and push

env:
  DOCKERHUB_USERNAME: erictik
  APPVERSION: v1.1.${{ github.run_number }}
  TAG: erictik/${{ github.event.repository.name }}:v1.1.${{ github.run_number }}
  LATEST_TAG: erictik/${{ github.event.repository.name }}:latest
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '**.ts'
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # - name: private npm registry
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=${{secrets.GIT_TOKEN || github.token}}" > ~/.npmrc
      - name: run build
        run: yarn install && yarn build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.APPVERSION  }}
          target_commitish: ${{ github.sha }}
